Add workflow to install Python code, run tests, and submit coverage report
myome/actions pull request #29
Opened 2023-01-19 22:15 UTC by dylan-myome

Branching off of a conversation @bwinnacott and I had about adding code coverage as an action, it seemed like it might be more valuable to create a standard workflow for testing and reporting coverage of our Python code repos

2023-01-21 00:41 UTC, ScottCruzen0 approved these changes
Looks good, probably needs to be merged to try it?

2023-01-23 04:01 UTC, alavertu reviewed
It'll be a nice addition to our python CI/CD workflow. I made some comments in-line

2023-01-23 16:44 UTC, sorozco07 approved these changes
This looks good! Although, if we want this to become standard in all repos, then probably also worth adding it to the [myome/example](https://github.com/myome/example/tree/main/.github/workflows) template.

2023-01-23 16:46 UTC, sorozco07 commented on .github/workflows/test-and-report.yaml
> +        make test
The myome/example repo does have pytest in Makefile. But I agree in removing a Makefile dependency.

2023-01-24 05:31 UTC, reece requested changes
Two requests.

1) Please explain the relationship of this new file to the existing files with overlapping functionality.

2) Please migrate functionality to the top level Makefile so that we're (nearly) guaranteed to run testing, linting, reformatting, etc the same way in local and github actions environments.

2023-01-24 05:31 UTC, reece commented on .github/workflows/test-and-report.yaml
> +        make test
Let's please converge on the Makefile as the definitive way to run commands. The rationale is that we want people to be able to run these commands locally exactly the same way that they do in github actions. If we put these in the Makefile and actions, then eventually we'll modify one but not the other and get different behavior.

2023-01-24 05:31 UTC, reece commented on .github/workflows/test-and-report.yaml
> +        bandit -ll -r ${{ SRC_PATH }}
Please put this command in the Makefile.

2023-01-24 05:31 UTC, reece commented on .github/workflows/test-and-report.yaml
> +        black --check ${{ SRC_PATH }}
Please put this command in the Makefile.

2023-01-24 18:26 UTC, bwinnacott commented
@reece This would provide a single location from which all python repos can call a quality analysis and testing workflow for CI/CD. As a result, if we need to make any modifications to the methods, we only need to update in one place as opposed to all the repos that use them. So, the python repos that call this workflow would have the `cqa` and `test` jobs removed and combined here instead. Might look something like this: 
```
on:
  push:
  pull_request:

jobs:
  test_and_report:
    uses: myome/actions/.github/workflows/test-and-report.yaml@main
  deploy:
    needs: test_and_report
    ...
```
Combining them into a single job also removes the need to run redundant steps multiple times in a single CI/CD workflow (setup python, install dependencies, etc.). Basically, this would replace and centralize the overlapping functionality in the existing `python-package.yml` files.

2023-02-14 01:48 UTC, reece commented
@bwinnacott: Yikes. Sorry for the delay. I didn't see the mention and this didn't come up in my review queue because I'd already reviewed. 

Yep, I get that the goal here is to consolidate actions across repos. I wholly support that.

In addition, I would like to ensure that there's exactly one way to run tests, cqa, reformatting, etc across all packages, and that these commands are identical when executed locally (during development) and in github actions. I've wasted a lot of time debugging failures in one context that aren't in the other because of invocation or config differences.

In practice, I think this means putting the meat of all of these commands in a Makefile and invoking that make target from the action. See my [previous comment](https://github.com/myome/actions/pull/29#pullrequestreview-1266796012).

2023-02-28 00:46 UTC, alavertu approved these changes
lgtm, will be good to consolidate around this and extend later if we'd like

2023-02-28 00:52 UTC, merged